---
version: '3.8'
services:

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demo
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_db.sql:/docker-entrypoint-initdb.d/postgres_db.sql
    command: 'postgres --max_prepared_transactions=100'

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'demo'
      MYSQL_USER: 'demo'
      MYSQL_PASSWORD: 'demo'
      MYSQL_ROOT_PASSWORD: 'demo'
    volumes:
      - ./mysql_db.sql:/docker-entrypoint-initdb.d/mysql_db.sql
    ports:
      - '3306:3306'
    expose:
      - '3306'

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 6060:8080

  activemq:
    image: registry.redhat.io/amq7/amq-broker:latest
    container_name: activemq
    environment:
      - AMQ_USER=admin
      - AMQ_PASSWORD=admin
    ports:
      - "61616:61616"
      - "8161:8161"
