---
version: '3.8'
services:

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demo
    ports:
      - '5432:5432'
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  activemq:
    image: registry.redhat.io/amq7/amq-broker:latest
    container_name: activemq
    environment:
      - AMQ_USER=admin
      - AMQ_PASSWORD=admin
#    volumes:
#      - "./activemq/activemq.xml:/conf/activemq.xml"
    ports:
      - "61616:61616"
      - "8161:8161"

networks:
  camel-saga:
    driver: custom-driver-1